/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;


import br.com.model.tablemodel.TransacaoTableModel;
import br.com.controller.ClienteController;
import br.com.controller.TransacaoController;
import br.com.controller.VendedorController;
import br.com.model.negocio.Cliente;
import br.com.model.negocio.Transacao;
import br.com.model.negocio.Vendedor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author MEUS DOCUMENTOS
 */
public class AtualizarTransacaoGui extends javax.swing.JFrame {

    int linhaSelecionada;
    int codigoMarca;
    TransacaoTableModel model;

    /**
     * Creates new form InserirMarcaGui
     */
    public AtualizarTransacaoGui(int selecionado, int cdTransacao, TransacaoTableModel mtb) {
        initComponents();
        txId.setEditable(false);
        linhaSelecionada = selecionado;
        cdTransacao = cdTransacao;
        model = mtb;
        
        TransacaoController tc = new TransacaoController();
        Transacao t = new Transacao();
        t = tc.listarTransacaoById(cdTransacao);

        txId.setText(Integer.toString(t.getCodigo()));
        campoProduto.setText(t.getProduto());
            
        carregarComboC(t.getCliente().getId()); 
        carregarComboV(t.getVendedor().getId()); 
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        botaoSalvar = new javax.swing.JButton();
        labelCodigo = new javax.swing.JLabel();
        txId = new javax.swing.JTextField();
        campoProduto = new javax.swing.JTextField();
        labelProduto = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        comboCliente = new javax.swing.JComboBox();
        labelVendedor = new javax.swing.JLabel();
        comboVendedor = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Marca");

        painelFundo.setBackground(new java.awt.Color(102, 102, 102));
        painelFundo.setLayout(null);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("Atualizar Transacão");
        painelFundo.add(labelTitulo);
        labelTitulo.setBounds(57, 11, 190, 22);

        botaoSalvar.setBackground(new java.awt.Color(255, 255, 255));
        botaoSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoSalvar.setForeground(new java.awt.Color(102, 102, 102));
        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });
        painelFundo.add(botaoSalvar);
        botaoSalvar.setBounds(310, 195, 80, 40);

        labelCodigo.setBackground(new java.awt.Color(255, 255, 255));
        labelCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCodigo.setForeground(new java.awt.Color(255, 255, 255));
        labelCodigo.setText("Codigo.:");
        painelFundo.add(labelCodigo);
        labelCodigo.setBounds(10, 50, 60, 20);

        txId.setEditable(false);
        painelFundo.add(txId);
        txId.setBounds(90, 50, 82, 20);

        campoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoProdutoActionPerformed(evt);
            }
        });
        painelFundo.add(campoProduto);
        campoProduto.setBounds(90, 80, 300, 20);

        labelProduto.setBackground(new java.awt.Color(255, 255, 255));
        labelProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelProduto.setForeground(new java.awt.Color(255, 255, 255));
        labelProduto.setText("Produto.:  ");
        painelFundo.add(labelProduto);
        labelProduto.setBounds(10, 80, 70, 20);

        labelCliente.setBackground(new java.awt.Color(255, 255, 255));
        labelCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCliente.setForeground(new java.awt.Color(255, 255, 255));
        labelCliente.setText("Cliente.:  ");
        painelFundo.add(labelCliente);
        labelCliente.setBounds(10, 120, 100, 20);

        comboCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        painelFundo.add(comboCliente);
        comboCliente.setBounds(90, 120, 190, 20);

        labelVendedor.setBackground(new java.awt.Color(255, 255, 255));
        labelVendedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelVendedor.setForeground(new java.awt.Color(255, 255, 255));
        labelVendedor.setText("Vendedor.:  ");
        painelFundo.add(labelVendedor);
        labelVendedor.setBounds(10, 160, 80, 20);

        comboVendedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        painelFundo.add(comboVendedor);
        comboVendedor.setBounds(90, 160, 190, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        Transacao t = new Transacao();
        

       
            t.setCodigo(Integer.parseInt(txId.getText()));
            t.setProduto(campoProduto.getText());
            t.setCliente((Cliente)comboCliente.getSelectedItem());
            t.setVendedor((Vendedor)comboVendedor.getSelectedItem());
            TransacaoController mc = new TransacaoController();
           if( mc.salvar(t)){
            model.updateTransacao(linhaSelecionada, t);
           }
            dispose();


        
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void campoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoProdutoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoProduto;
    private javax.swing.JComboBox comboCliente;
    private javax.swing.JComboBox comboVendedor;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelProduto;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVendedor;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JTextField txId;
    // End of variables declaration//GEN-END:variables

 private void carregarComboC(int cdCliente) {
         //assim como é feito numa JTable, temos o DefaultComboBoxModel que é o model do JComboBox
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) comboCliente.getModel();
        //removendo todos os elementos do combo
        comboModel.removeAllElements();
        //cria a lista: java.util.List
        List<Cliente> clientes = new ArrayList<Cliente>();
        ClienteController a = new ClienteController();
        clientes = a.listarCliente();
        
     
        for (int linha = 0; linha < clientes.size(); linha++) {
            //pegando a categoria da lista
            Cliente cliente = clientes.get(linha);
            //adicionando a categoria no combo
            comboModel.addElement(cliente);
            if ( cliente.getId() == cdCliente){
                comboModel.setSelectedItem(cliente);
            }
            
        }
        
    }
 
 private void carregarComboV(int cdVendedor) {
         //assim como é feito numa JTable, temos o DefaultComboBoxModel que é o model do JComboBox
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) comboVendedor.getModel();
        //removendo todos os elementos do combo
        comboModel.removeAllElements();
        //cria a lista: java.util.List
        List<Vendedor> vendedores = new ArrayList<Vendedor>();
        VendedorController a = new VendedorController();
        vendedores = a.listarVendedor();
        
     
        for (int linha = 0; linha < vendedores.size(); linha++) {
            //pegando a categoria da lista
            Vendedor vendedor = vendedores.get(linha);
            //adicionando a categoria no combo
            comboModel.addElement(vendedor);
            if ( vendedor.getId() == cdVendedor){
                comboModel.setSelectedItem(vendedor);
            }
            
        }
        
    }
}
